---
name: str()
version: enum(1.0)
variables: map(str(), str())
compose: include('compose', required=True)
command: map(str, include('command', required=True))

---
compose:
  include: str()

---
command:
  in: enum('local', 'container')
  container: str()
  interpreter: enum('sh')
  content: any(str(), list(str()))
