---
name: str()
version: enum(1.0)
variables: map(str(), str())
compose: include('compose', required=True)
command: map(str, include('command', required=True))

---
compose:
  include: str(required=True)

---
command:
  env: enum('local', 'container', 'self', required=True)
  container: str(required=False)
  interpreter: enum('sh', required=False)
  content: any(str(), list(str()), required=True)
